# Generated by Django 3.2.16 on 2023-06-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['pub_date']},
        ),
    ]
